@Cryptography.App_HostAddress = https://localhost:44390


POST {{Cryptography.App_HostAddress}}/hill-encrypt  
Content-Type: application/json
{  
  "plaintext": "Hello World!1"  
}  

POST {{Cryptography.App_HostAddress}}/hill-decrypt  
Content-Type: application/json  
{  
  "ciphertext": "HIOZEIPJQL"  
}